version: "2"
services:
  eventtracker:
    container_name: event_tracker
    build: .
    command: event-tracker
    environment:
      - EVENT_TRACKER_PORT="3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/github.com/rafaeljesus/event-tracker
    links:
      - elasticsearch
      - kafka

  elasticsearch:
    container_name: dev_elasticsearch
    image: elasticsearch:1.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /Users/rafaeljesus/mnt/sda1/data/elasticsearch:/usr/share/elasticsearch/data

  kafka:
    container_name: dev_kafka
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    volumes:
      - /Users/rafaeljesus/mnt/sda1/data/kafka:/usr/share/kafka/data

  zookeeper:
    container_name: dev_zookeeper
    image: oddpoet/zookeeper
    hostname: zookeeper
    command:
      - "2181"
    ports:
      - "2181:2181"
